const TESTNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES = new Map<string, string>([
  ['MATIC', '0x739C7be95192d8eED70263b92CAA0720c1E8eD77'],
  ['XDC', '0x74E17c7eAE74D346808bCcf9C476aDa18608bCB2']
])

const MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES = new Map<string, string>([])

const SMART_SAFE_CHAINS_ENV_ADRESSES = new Map([
  ['production', MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES],
  ['development', TESTNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES]
])

export const SMART_SAFE_FACTORY_CHAINS_ADRESSES =
  SMART_SAFE_CHAINS_ENV_ADRESSES.get(
    process.env.NEXT_PUBLIC_ENV ?? 'production'
  ) ?? MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES
