const TESTNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES = new Map<string, string>([
  ['MATIC', '0x12D7b9763AA1fa4da517421fDC953260D80bf205']
])

const MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES = new Map<string, string>([])

const SMART_SAFE_CHAINS_ENV_ADRESSES = new Map([
  ['production', MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES],
  ['development', TESTNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES]
])

export const SMART_SAFE_FACTORY_CHAINS_ADRESSES =
  SMART_SAFE_CHAINS_ENV_ADRESSES.get(
    process.env.NEXT_PUBLIC_ENV ?? 'production'
  ) ?? MAINNET_SMART_SAFE_CHAINS_FACTORY_ADRESSES
