/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SmartSafeFactory,
  SmartSafeFactoryInterface,
} from "../SmartSafeFactory";

const _abi = [
  {
    inputs: [],
    name: "InvalidContractAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "Deployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_owners",
        type: "address[]",
      },
      {
        internalType: "uint8",
        name: "_threshold",
        type: "uint8",
      },
    ],
    name: "deploySmartSafe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_owners",
        type: "address[]",
      },
      {
        internalType: "uint8",
        name: "_threshold",
        type: "uint8",
      },
    ],
    name: "computeAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SmartSafeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): SmartSafeFactoryInterface {
    return new utils.Interface(_abi) as SmartSafeFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmartSafeFactory {
    return new Contract(address, _abi, signerOrProvider) as SmartSafeFactory;
  }
}
